FROM node:18

WORKDIR /usr/src/app
COPY ./package*.json ./

RUN cat package.json
RUN npm install

RUN echo $PWD
RUN ls -lah .
# If you are building your code for production
# RUN npm ci --only=production

COPY . .

RUN npm run build

CMD [ "npm", "run", "start" ]