FROM golang:1.18-bullseye

WORKDIR /usr/src/app

COPY ./go-gin/go.mod ./go-gin/go.sum ./
RUN go mod download && go mod verify

COPY ./go-gin .
RUN ls -lah /usr/local/
# RUN mkdir -p /usr/local/bin/app
RUN go build -v -o /usr/local/bin/ ./...
RUN ls -lah /usr/local/bin/
CMD ["go-gingonic-bench3"]