# FROM registry.gitlab.com/leogouveia/containers/php-alpine
FROM php:8.1-alpine
ARG user
ARG uid

# # # Install system dependencies
# RUN apt-get update && apt-get install -y \
#     git \
#     curl \
#     libpng-dev \
#     libonig-dev \
#     libxml2-dev \
#     zip \
#     unzip \
#     libpq-dev \
#     vim

# # Clear cache
# RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# # Install PHP extensions
# RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd pdo_pgsql

# # Get latest Composer
# COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# # Create system user to run Composer and Artisan Commands
# RUN useradd -G www-data,root -u $uid -d /home/$user $user
# RUN mkdir -p /home/$user/.composer && \
#     chown -R $user:$user /home/$user
# RUN chown $user:$user /usr/bin/composer

# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

COPY ./php-alpine/php.ini /etc/php8/php.ini
COPY ./php-alpine/00_opcache.ini /etc/php8/conf.d/00_opcache.ini
COPY ./php-alpine/php-fpm.conf /etc/php8/php-fpm.conf
COPY ./php-alpine/www.conf /etc/php8/php-fpm.d/www.conf

RUN adduser -D "${user}" -G www-data -u $uid -h /home/$user $user
# RUN chown -r $user:$user /home/$usr

# Set working directory
WORKDIR /var/www
COPY ./laravel /var/www/laravel
RUN chmod 775 -R /var/www/laravel/storage

COPY ./php-lumen /var/www/lumen
RUN chmod 775 /var/www/lumen

# USER $user
